kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: python
    commands:
      - pip install -r requirements.txt
      - coverage run -m pytest --ignore=gitlab
      - coverage report --show-missing